### ISSUE TITLE
前端路由的权限管理如何实现的

### ISSUE THREAD

**Issue by hainuo** [liujians/vue-adminLte-vue-router#1]
如题，如何对路由实现权限管理

**Comment by liujians** [comment]
我们的项目中使用node做拦截，redirect或者next、菜单相关分配都会放到DB层去做

**Comment by hainuo** [comment]
了解 还是在后端判断啊 
------------------ 原始邮件 ------------------
发件人: "刘剑"notifications@github.com
发送时间: 2016年11月6日(星期天) 上午9:38
收件人: "liujians/vue-adminLte-vue-router"vue-adminLte-vue-router@noreply.github.com;
抄送: "hainuo"admin@hainuo.info;"Author"author@noreply.github.com;
主题: Re: [liujians/vue-adminLte-vue-router] 前端路由的权限管理如何实现的 (#1)

我们的项目中使用node做拦截，redirect或者next、菜单相关分配都会放到DB层去做

&mdash;
