### ISSUE TITLE
npm run dev error

### ISSUE THREAD

**Issue by gyamxxx** [liujians/vue-adminLte-vue-router#2]
I try to exec "npm run dev" after "npm install", but these error occur.

  	ERROR in ./src/main.js
	Module not found: Error: Cannot resolve 'file' or 'directory' ./dist/css/skins/_all-skins.min.css in /tmpi/Documents/vue-adminLte-vue-router/src
	 @ ./src/main.js 5:0-57
	
	ERROR in ./src/main.js
	Module not found: Error: Cannot resolve 'file' or 'directory' ./dist/css/AdminLTE.min.css in /tmpi/Documents/vue-adminLte-vue-router/src
	 @ ./src/main.js 6:0-49
	
	ERROR in ./src/main.js
	Module not found: Error: Cannot resolve 'file' or 'directory' ./dist/js/demo.js in /tmpi/Documents/vue-adminLte-vue-router/src
	 @ ./src/main.js 19:0-28
	
	ERROR in ./src/main.js
	Module not found: Error: Cannot resolve 'file' or 'directory' ./dist/js/app.min.js in /tmpi/Documents/vue-adminLte-vue-router/src
	 @ ./src/main.js 20:0-31
	
	ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-acbab0e2!./~/vue-loader/lib/selector.js?type=template&index=0!./src/index.vue
	Module not found: Error: Cannot resolve 'file' or 'directory' ./dist/img/user2-160x160.jpg in /tmpi/Documents/vue-adminLte-vue-router/src
	 @ ./~/vue-loader/lib/template-compiler.js?id=data-v-acbab0e2!./~/vue-loader/lib/selector.js?type=template&index=0!./src/index.vue 156:13-52 168:13-52 196:13-52
	Child html-webpack-plugin for "index.html":
	         Asset     Size  Chunks       Chunk Names
	    index.html  1.46 MB       0

**Comment by liujians** [comment]
@gyamxxx fixed    please pull The latest

**Comment by gyamxxx** [comment]
thx! fixed it. good work.
