### ISSUE TITLE
npm run dev error

### ISSUE THREAD

**Issue by Liaoer** [liujians/vue-adminLte-vue-router#3]
WARNING in ./src/plugins/daterangepicker/moment.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./locale in /Users/liao/Documents/GitHub/vue-adminLte-vue-router/src/plugins/daterangepicker
 @ ./src/plugins/daterangepicker/moment.js 1:4485-4510

**Comment by ljinglun** [comment]
same error , Encounter the same problem，if you found the solutio, I hope you can share it.

**Comment by liujians** [comment]
I don't know what happened, I updated, please try to pull the last @Liaoer

**Comment by liujians** [comment]
@chinalijinglun fixed it,Try the latest version

**Comment by unadlib** [comment]
mkdir -p vue-adminLte-vue-router-master/src/plugins/daterangepicker/locale/
Because the locale folder is missing.

**Comment by liujians** [comment]
@Liaoer @chinalijinglun @unadlib  good work,i got it,
