### ISSUE TITLE
移动端点完菜单后左侧菜单栏没有隐藏，体验不好

### ISSUE THREAD

**Issue by xixiyang1216** [liujians/vue-adminLte-vue-router#5]
项目做得很棒，pc和移动完美适配又很美观，希望可以帮移动端显示时左侧菜单栏select完之后能够收回去

**Comment by liujians** [comment]
感谢反馈、会尽快优化，修改过后会第一时间发布 @xixiyang1216

**Comment by liujians** [comment]
@xixiyang1216 已更新、Please pull the latest
